# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_namesoup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='word_type',
        ),
        migrations.AddField(
            model_name='type',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Word'),
        ),
    ]
