# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170208_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='english',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
