# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_word_english'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='english',
        ),
        migrations.AlterField(
            model_name='word',
            name='gender',
            field=models.CharField(default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='englishword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Word'),
        ),
    ]
