# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170213_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
